# Generated by Django 4.2.8 on 2025-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address to which OTP is sent', max_length=255)),
                ('otp', models.CharField(help_text='6-digit numeric OTP code', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp for the OTP (typically 10 minutes from creation)')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts (max 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'db_table': 'email_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'expires_at'], name='email_otps_email_a8cbda_idx'), models.Index(fields=['created_at'], name='email_otps_created_5102ba_idx')],
            },
        ),
    ]
