# Generated by Django 4.2.8 on 2025-12-26 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('language', models.CharField(help_text='Language in which the event will be conducted', max_length=100)),
                ('location', models.CharField(help_text='Physical or virtual location of the event', max_length=255)),
                ('starts_at', models.DateTimeField(help_text='Event start time in UTC')),
                ('ends_at', models.DateTimeField(help_text='Event end time in UTC')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (null means unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Facilitator who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('canceled', 'Canceled')], default='enrolled', help_text='Current enrollment status', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='events.event')),
                ('seeker', models.ForeignKey(help_text='The seeker enrolling in the event', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_starts__f39f74_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_locatio_2a4a74_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_created_2c88fa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_created_9e2206_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['event', 'status'], name='enrollments_event_i_cd4a18_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['seeker', 'status'], name='enrollments_seeker__d698c4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_at'], name='enrollments_enrolle_00c691_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('event', 'seeker')},
        ),
    ]
